// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'album_response.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$_AlbumResponse _$$_AlbumResponseFromJson(Map<String, dynamic> json) =>
    _$_AlbumResponse(
      status: json['status'] as String?,
      data: (json['data'] as List<dynamic>?)
          ?.map((e) => Album.fromJson(e as Map<String, dynamic>))
          .toList(),
      message: json['message'] as String?,
      error: json['error'],
    );

Map<String, dynamic> _$$_AlbumResponseToJson(_$_AlbumResponse instance) =>
    <String, dynamic>{
      'status': instance.status,
      'data': instance.data,
      'message': instance.message,
      'error': instance.error,
    };

_$_Album _$$_AlbumFromJson(Map<String, dynamic> json) => _$_Album(
      isLiked: json['isLiked'] as bool?,
      userId: json['userId'] as String?,
      userName: json['userName'] as String?,
      fullName: json['fullName'] as String?,
      userImage: json['userImage'] as String?,
      isInvisible: json['isInvisible'] as String?,
      albumId: json['albumId'] as String?,
      viewId: json['viewId'] as String?,
      privacy: json['privacy'] as String?,
      privacyComment: json['privacyComment'] as String?,
      isFeatured: json['isFeatured'] as String?,
      isSponsor: json['isSponsor'] as String?,
      name: json['name'] as String?,
      year: json['year'] as String?,
      genreId: json['genreId'] as String?,
      isDj: json['isDj'] as String?,
      licenseType: json['licenseType'] as String?,
      imagePath: json['imagePath'] as String?,
      serverId: json['serverId'] as String?,
      totalTrack: json['totalTrack'] as String?,
      totalPlay: json['totalPlay'] as String?,
      totalComment: json['totalComment'] as String?,
      totalView: json['totalView'] as String?,
      totalLike: json['totalLike'] as String?,
      totalDislike: json['totalDislike'] as String?,
      totalScore: json['totalScore'] as String?,
      totalRating: json['totalRating'] as String?,
      totalAttachment: json['totalAttachment'] as String?,
      timeStamp: json['timeStamp'] as String?,
      moduleId: json['moduleId'],
      itemId: json['itemId'] as String?,
      isDay: json['isDay'],
      artistId: json['artistId'] as String?,
      itunes: json['itunes'] as String?,
      amazon: json['amazon'] as String?,
      googleplay: json['googleplay'] as String?,
      youtube: json['youtube'],
      soundcloud: json['soundcloud'] as String?,
      labelUser: json['labelUser'] as String?,
      labelUserId: json['labelUserId'] as String?,
      artistUser: json['artistUser'] as String?,
      artistUserId: json['artistUserId'] as String?,
      collabUser: json['collabUser'] as String?,
      collabUserId: json['collabUserId'] as String?,
      canEdit: json['canEdit'] as bool?,
      canAddSong: json['canAddSong'] as bool?,
      canDelete: json['canDelete'] as bool?,
      canPurchaseSponsor: json['canPurchaseSponsor'] as bool?,
      canSponsor: json['canSponsor'] as bool?,
      canFeature: json['canFeature'] as bool?,
      hasPermission: json['hasPermission'] as bool?,
    );

Map<String, dynamic> _$$_AlbumToJson(_$_Album instance) => <String, dynamic>{
      'isLiked': instance.isLiked,
      'userId': instance.userId,
      'userName': instance.userName,
      'fullName': instance.fullName,
      'userImage': instance.userImage,
      'isInvisible': instance.isInvisible,
      'albumId': instance.albumId,
      'viewId': instance.viewId,
      'privacy': instance.privacy,
      'privacyComment': instance.privacyComment,
      'isFeatured': instance.isFeatured,
      'isSponsor': instance.isSponsor,
      'name': instance.name,
      'year': instance.year,
      'genreId': instance.genreId,
      'isDj': instance.isDj,
      'licenseType': instance.licenseType,
      'imagePath': instance.imagePath,
      'serverId': instance.serverId,
      'totalTrack': instance.totalTrack,
      'totalPlay': instance.totalPlay,
      'totalComment': instance.totalComment,
      'totalView': instance.totalView,
      'totalLike': instance.totalLike,
      'totalDislike': instance.totalDislike,
      'totalScore': instance.totalScore,
      'totalRating': instance.totalRating,
      'totalAttachment': instance.totalAttachment,
      'timeStamp': instance.timeStamp,
      'moduleId': instance.moduleId,
      'itemId': instance.itemId,
      'isDay': instance.isDay,
      'artistId': instance.artistId,
      'itunes': instance.itunes,
      'amazon': instance.amazon,
      'googleplay': instance.googleplay,
      'youtube': instance.youtube,
      'soundcloud': instance.soundcloud,
      'labelUser': instance.labelUser,
      'labelUserId': instance.labelUserId,
      'artistUser': instance.artistUser,
      'artistUserId': instance.artistUserId,
      'collabUser': instance.collabUser,
      'collabUserId': instance.collabUserId,
      'canEdit': instance.canEdit,
      'canAddSong': instance.canAddSong,
      'canDelete': instance.canDelete,
      'canPurchaseSponsor': instance.canPurchaseSponsor,
      'canSponsor': instance.canSponsor,
      'canFeature': instance.canFeature,
      'hasPermission': instance.hasPermission,
    };
