name: audio_cult
description: AudioCult
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  bloc: ^8.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_svg: ^1.0.3
  cached_network_image: ^3.2.0
  flutter_speed_dial: ^5.0.0+1
  badges: ^2.0.2
  flutter_custom_tab_bar: ^1.1.9
  textfield_tags: ^1.4.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  get_it: ^7.2.0
  dio: ^4.0.4
  provider: ^6.0.2
  shared_preferences: ^2.0.13
  rxdart: ^0.27.3
  infinite_scroll_pagination: ^3.1.0
  responsive_framework: ^0.1.5
  page_transition: ^2.0.5
  connectivity_plus: ^2.2.0
  very_good_analysis: ^2.4.0
  dartz: ^0.10.1
  loader_overlay: ^2.0.5
  loading_indicator: ^3.0.2
  disposing: ^1.0.3+1

dev_dependencies:
  bloc_test: ^9.0.2
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/icons/
    - assets/fonts/
    - assets/imgs/
  fonts:
  - family: NunitoSans
    fonts:
      - asset: assets/fonts/NunitoSans-Regular.ttf
        weight: 100
      - asset: assets/fonts/NunitoSans-Light.ttf
        weight: 300
      - asset: assets/fonts/NunitoSans-Regular.ttf
        weight: 400
      - asset: assets/fonts/NunitoSans-Bold.ttf
        weight: 500
      - asset: assets/fonts/NunitoSans-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/NunitoSans-Bold.ttf
        weight: 700
      - asset: assets/fonts/NunitoSans-ExtraBold.ttf
        weight: 900