// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'playlist_response.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$_PlaylistResponse _$$_PlaylistResponseFromJson(Map<String, dynamic> json) =>
    _$_PlaylistResponse(
      isLiked: json['isLiked'] as String?,
      userId: json['userId'] as String?,
      profilePageId: json['profilePageId'] as String?,
      userServerId: json['userServerId'] as String?,
      userName: json['user_name'] as String?,
      fullName: json['full_name'] as String?,
      gender: json['gender'] as String?,
      userImage: json['userImage'] as String?,
      isInvisible: json['isInvisible'] as String?,
      userGroupId: json['userGroupId'] as String?,
      languageId: json['languageId'] as String?,
      lastActivity: json['lastActivity'] as String?,
      birthday: json['birthday'] as String?,
      countryIso: json['countryIso'] as String?,
      playlistId: json['playlist_id'] as String?,
      title: json['title'] as String?,
      description: json['description'] as String?,
      timeStamp: json['time_stamp'] as String?,
      totalLikes: json['total_likes'] as String?,
      totalComments: json['total_comments'] as String?,
      isFeatured: json['isFeatured'] as bool?,
      imagePath: json['image_path'] as String?,
      isDay: json['isDay'] as bool?,
      totalView: json['total_view'] as String?,
      artistId: json['artistId'] as String?,
      songs: (json['songs'] as List<dynamic>?)
          ?.map((e) => Songs.fromJson(e as Map<String, dynamic>))
          .toList(),
      countSongs: json['count_songs'] as int?,
    );

Map<String, dynamic> _$$_PlaylistResponseToJson(_$_PlaylistResponse instance) =>
    <String, dynamic>{
      'isLiked': instance.isLiked,
      'userId': instance.userId,
      'profilePageId': instance.profilePageId,
      'userServerId': instance.userServerId,
      'user_name': instance.userName,
      'full_name': instance.fullName,
      'gender': instance.gender,
      'userImage': instance.userImage,
      'isInvisible': instance.isInvisible,
      'userGroupId': instance.userGroupId,
      'languageId': instance.languageId,
      'lastActivity': instance.lastActivity,
      'birthday': instance.birthday,
      'countryIso': instance.countryIso,
      'playlist_id': instance.playlistId,
      'title': instance.title,
      'description': instance.description,
      'time_stamp': instance.timeStamp,
      'total_likes': instance.totalLikes,
      'total_comments': instance.totalComments,
      'isFeatured': instance.isFeatured,
      'image_path': instance.imagePath,
      'isDay': instance.isDay,
      'total_view': instance.totalView,
      'artistId': instance.artistId,
      'songs': instance.songs,
      'count_songs': instance.countSongs,
    };

_$_Songs _$$_SongsFromJson(Map<String, dynamic> json) => _$_Songs(
      id: json['id'] as String?,
      songId: json['songId'] as String?,
      playlistId: json['playlistId'] as String?,
      userId: json['userId'] as String?,
      timeStamp: json['timeStamp'] as String?,
      profilePageId: json['profilePageId'] as String?,
      serverId: json['serverId'] as String?,
      userGroupId: json['userGroupId'] as String?,
      statusId: json['statusId'] as String?,
      viewId: json['viewId'] as String?,
      userName: json['userName'] as String?,
      fullName: json['fullName'] as String?,
      password: json['password'] as String?,
      passwordSalt: json['passwordSalt'] as String?,
      email: json['email'] as String?,
      gender: json['gender'] as String?,
      birthday: json['birthday'] as String?,
      birthdaySearch: json['birthdaySearch'] as String?,
      countryIso: json['countryIso'] as String?,
      languageId: json['languageId'] as String?,
      styleId: json['styleId'] as String?,
      timeZone: json['timeZone'],
      dstCheck: json['dstCheck'] as String?,
      joined: json['joined'] as String?,
      lastLogin: json['lastLogin'] as String?,
      lastActivity: json['lastActivity'] as String?,
      userImage: json['userImage'] as String?,
      hideTip: json['hideTip'] as String?,
      status: json['status'],
      footerBar: json['footerBar'] as String?,
      inviteUserId: json['inviteUserId'] as String?,
      imBeep: json['imBeep'] as String?,
      imHide: json['imHide'] as String?,
      isInvisible: json['isInvisible'] as String?,
      totalSpam: json['totalSpam'] as String?,
      lastIpAddress: json['lastIpAddress'] as String?,
      feedSort: json['feedSort'] as String?,
      customGender: json['customGender'] as String?,
      totalProfileLike: json['totalProfileLike'] as String?,
      isVerified: json['isVerified'] as String?,
      reminderDate: json['reminderDate'] as String?,
      blogRating: (json['blogRating'] as num?)?.toDouble(),
      privacy: json['privacy'] as String?,
      privacyComment: json['privacyComment'] as String?,
      isFree: json['isFree'] as String?,
      isFeatured: json['isFeatured'] as String?,
      isSponsor: json['isSponsor'] as String?,
      albumId: json['albumId'] as String?,
      genreId: json['genreId'] as String?,
      isDj: json['isDj'] as String?,
      title: json['title'] as String?,
      description: json['description'] as String?,
      descriptionParsed: json['descriptionParsed'] as String?,
      licenseType: json['licenseType'] as String?,
      songPath: json['songPath'] as String?,
      explicit: json['explicit'] as String?,
      duration: json['duration'] as String?,
      ordering: json['ordering'] as String?,
      imageServerId: json['imageServerId'] as String?,
      totalPlay: json['totalPlay'] as String?,
      totalView: json['totalView'] as String?,
      totalComment: json['totalComment'] as String?,
      totalLike: json['totalLike'] as String?,
      totalDislike: json['totalDislike'] as String?,
      totalScore: json['totalScore'] as String?,
      totalRating: json['totalRating'] as String?,
      totalAttachment: json['totalAttachment'] as String?,
      moduleId: json['moduleId'] as int?,
      itemId: json['itemId'] as String?,
      disableDownload: json['disableDownload'] as String?,
      isrc: json['isrc'] as String?,
      url: json['url'] as String?,
      isDay: json['isDay'] as String?,
      artistId: json['artistId'] as String?,
      lyrics: json['lyrics'] as String?,
      cost: json['cost'] as String?,
      totalDownload: json['totalDownload'] as int?,
      tags: json['tags'] as String?,
      itunes: json['itunes'] as String?,
      amazon: json['amazon'] as String?,
      googleplay: json['googleplay'] as String?,
      youtube: json['youtube'] as String?,
      soundcloud: json['soundcloud'] as String?,
      imagePath: json['imagePath'] as String?,
      labelUser: json['labelUser'] as String?,
      labelUserId: json['labelUserId'] as String?,
      artistUser: json['artistUser'] as String?,
      artistUserId: json['artistUserId'] as String?,
      collabUser: json['collabUser'] as String?,
      collabUserId: json['collabUserId'] as String?,
      peaksJsonUrl: json['peaksJsonUrl'] as String?,
      titleTruncate: json['titleTruncate'] as String?,
      noPhoto: json['noPhoto'] as int?,
    );

Map<String, dynamic> _$$_SongsToJson(_$_Songs instance) => <String, dynamic>{
      'id': instance.id,
      'songId': instance.songId,
      'playlistId': instance.playlistId,
      'userId': instance.userId,
      'timeStamp': instance.timeStamp,
      'profilePageId': instance.profilePageId,
      'serverId': instance.serverId,
      'userGroupId': instance.userGroupId,
      'statusId': instance.statusId,
      'viewId': instance.viewId,
      'userName': instance.userName,
      'fullName': instance.fullName,
      'password': instance.password,
      'passwordSalt': instance.passwordSalt,
      'email': instance.email,
      'gender': instance.gender,
      'birthday': instance.birthday,
      'birthdaySearch': instance.birthdaySearch,
      'countryIso': instance.countryIso,
      'languageId': instance.languageId,
      'styleId': instance.styleId,
      'timeZone': instance.timeZone,
      'dstCheck': instance.dstCheck,
      'joined': instance.joined,
      'lastLogin': instance.lastLogin,
      'lastActivity': instance.lastActivity,
      'userImage': instance.userImage,
      'hideTip': instance.hideTip,
      'status': instance.status,
      'footerBar': instance.footerBar,
      'inviteUserId': instance.inviteUserId,
      'imBeep': instance.imBeep,
      'imHide': instance.imHide,
      'isInvisible': instance.isInvisible,
      'totalSpam': instance.totalSpam,
      'lastIpAddress': instance.lastIpAddress,
      'feedSort': instance.feedSort,
      'customGender': instance.customGender,
      'totalProfileLike': instance.totalProfileLike,
      'isVerified': instance.isVerified,
      'reminderDate': instance.reminderDate,
      'blogRating': instance.blogRating,
      'privacy': instance.privacy,
      'privacyComment': instance.privacyComment,
      'isFree': instance.isFree,
      'isFeatured': instance.isFeatured,
      'isSponsor': instance.isSponsor,
      'albumId': instance.albumId,
      'genreId': instance.genreId,
      'isDj': instance.isDj,
      'title': instance.title,
      'description': instance.description,
      'descriptionParsed': instance.descriptionParsed,
      'licenseType': instance.licenseType,
      'songPath': instance.songPath,
      'explicit': instance.explicit,
      'duration': instance.duration,
      'ordering': instance.ordering,
      'imageServerId': instance.imageServerId,
      'totalPlay': instance.totalPlay,
      'totalView': instance.totalView,
      'totalComment': instance.totalComment,
      'totalLike': instance.totalLike,
      'totalDislike': instance.totalDislike,
      'totalScore': instance.totalScore,
      'totalRating': instance.totalRating,
      'totalAttachment': instance.totalAttachment,
      'moduleId': instance.moduleId,
      'itemId': instance.itemId,
      'disableDownload': instance.disableDownload,
      'isrc': instance.isrc,
      'url': instance.url,
      'isDay': instance.isDay,
      'artistId': instance.artistId,
      'lyrics': instance.lyrics,
      'cost': instance.cost,
      'totalDownload': instance.totalDownload,
      'tags': instance.tags,
      'itunes': instance.itunes,
      'amazon': instance.amazon,
      'googleplay': instance.googleplay,
      'youtube': instance.youtube,
      'soundcloud': instance.soundcloud,
      'imagePath': instance.imagePath,
      'labelUser': instance.labelUser,
      'labelUserId': instance.labelUserId,
      'artistUser': instance.artistUser,
      'artistUserId': instance.artistUserId,
      'collabUser': instance.collabUser,
      'collabUserId': instance.collabUserId,
      'peaksJsonUrl': instance.peaksJsonUrl,
      'titleTruncate': instance.titleTruncate,
      'noPhoto': instance.noPhoto,
    };
