// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'song_detail_response.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

SongDetailResponse _$SongDetailResponseFromJson(Map<String, dynamic> json) =>
    SongDetailResponse(
      isLiked: json['is_liked'] as String?,
      isFriend: json['is_friend'] as bool?,
      songId: json['song_id'] as String?,
      viewId: json['view_id'] as String?,
      privacy: json['privacy'] as String?,
      privacyComment: json['privacy_comment'] as String?,
      isFree: json['is_free'] as String?,
      isFeatured: json['is_featured'] as String?,
      isSponsor: json['is_sponsor'] as String?,
      albumId: json['album_id'] as String?,
      genreId: json['genre_id'] as String?,
      isDj: json['is_dj'] as String?,
      userId: json['user_id'] as String?,
      title: json['title'] as String?,
      description: json['description'] as String?,
      descriptionParsed: json['description_parsed'] as String?,
      licenseType: json['license_type'] as String?,
      songPath: json['song_path'] as String?,
      serverId: json['server_id'] as String?,
      explicit: json['explicit'] as String?,
      duration: json['duration'] as int?,
      ordering: json['ordering'] as String?,
      imageServerId: json['image_server_id'] as String?,
      totalPlay: json['total_play'] as String?,
      totalView: json['total_view'] as String?,
      totalComment: json['total_comment'] as String?,
      totalLike: json['total_like'] as String?,
      totalDislike: json['total_dislike'] as String?,
      totalScore: json['total_score'] as String?,
      totalRating: json['total_rating'] as String?,
      totalAttachment: json['total_attachment'] as String?,
      timeStamp: json['time_stamp'] as String?,
      moduleId: json['module_id'] as String?,
      itemId: json['item_id'] as String?,
      disableDownload: json['disable_download'] as String?,
      isrc: json['isrc'] as String?,
      url: json['url'] as String?,
      isDay: json['is_day'] as String?,
      artistId: json['artist_id'] as String?,
      lyrics: json['lyrics'] as String?,
      cost: json['cost'] as String?,
      totalDownload: json['total_download'] as String?,
      tags: json['tags'] as String?,
      itunes: json['itunes'] as String?,
      amazon: json['amazon'] as String?,
      googleplay: json['googleplay'] as String?,
      youtube: json['youtube'] as String?,
      soundcloud: json['soundcloud'] as String?,
      imagePath: json['image_path'] as String?,
      labelUser: json['label_user'] == null
          ? null
          : LabelUser.fromJson(json['label_user'] as Map<String, dynamic>),
      labelUserId: json['label_user_id'] as String?,
      artistUser: json['artist_user'] == null
          ? null
          : ArtistUser.fromJson(json['artist_user'] as Map<String, dynamic>),
      artistUserId: json['artist_user_id'] as String?,
      collabUser: json['collab_user'] as String?,
      collabUserId: json['collab_user_id'] as String?,
      peaksJsonUrl: json['peaks_json_url'] as String?,
      genreName: json['genre_name'] as String?,
      songTotalComment: json['song_total_comment'] as String?,
      songTotalPlay: json['song_total_play'] as String?,
      songTimeStamp: json['song_time_stamp'] as String?,
      songIsSponsor: json['song_is_sponsor'] as String?,
      albumUrl: json['album_url'] as String?,
      isOnProfile: json['is_on_profile'] as bool?,
      profileUserId: json['profile_user_id'] as String?,
      profilePageId: json['profile_page_id'] as String?,
      userServerId: json['user_server_id'] as String?,
      userName: json['user_name'] as String?,
      fullName: json['full_name'] as String?,
      gender: json['gender'] as String?,
      userImage: json['user_image'] as String?,
      isInvisible: json['is_invisible'] as String?,
      userGroupId: json['user_group_id'] as String?,
      languageId: json['language_id'] as String?,
      lastActivity: json['last_activity'] as String?,
      birthday: json['birthday'] as String?,
      countryIso: json['country_iso'] as String?,
      realPath: json['real_path'] as String?,
      songPath64: json['song_path64'] as String?,
      bookmark: json['bookmark'] as String?,
    );

Map<String, dynamic> _$SongDetailResponseToJson(SongDetailResponse instance) =>
    <String, dynamic>{
      'is_liked': instance.isLiked,
      'is_friend': instance.isFriend,
      'song_id': instance.songId,
      'view_id': instance.viewId,
      'privacy': instance.privacy,
      'privacy_comment': instance.privacyComment,
      'is_free': instance.isFree,
      'is_featured': instance.isFeatured,
      'is_sponsor': instance.isSponsor,
      'album_id': instance.albumId,
      'genre_id': instance.genreId,
      'is_dj': instance.isDj,
      'user_id': instance.userId,
      'title': instance.title,
      'description': instance.description,
      'description_parsed': instance.descriptionParsed,
      'license_type': instance.licenseType,
      'song_path': instance.songPath,
      'server_id': instance.serverId,
      'explicit': instance.explicit,
      'duration': instance.duration,
      'ordering': instance.ordering,
      'image_server_id': instance.imageServerId,
      'total_play': instance.totalPlay,
      'total_view': instance.totalView,
      'total_comment': instance.totalComment,
      'total_like': instance.totalLike,
      'total_dislike': instance.totalDislike,
      'total_score': instance.totalScore,
      'total_rating': instance.totalRating,
      'total_attachment': instance.totalAttachment,
      'time_stamp': instance.timeStamp,
      'module_id': instance.moduleId,
      'item_id': instance.itemId,
      'disable_download': instance.disableDownload,
      'isrc': instance.isrc,
      'url': instance.url,
      'is_day': instance.isDay,
      'artist_id': instance.artistId,
      'lyrics': instance.lyrics,
      'cost': instance.cost,
      'total_download': instance.totalDownload,
      'tags': instance.tags,
      'itunes': instance.itunes,
      'amazon': instance.amazon,
      'googleplay': instance.googleplay,
      'youtube': instance.youtube,
      'soundcloud': instance.soundcloud,
      'image_path': instance.imagePath,
      'label_user': instance.labelUser,
      'label_user_id': instance.labelUserId,
      'artist_user': instance.artistUser,
      'artist_user_id': instance.artistUserId,
      'collab_user': instance.collabUser,
      'collab_user_id': instance.collabUserId,
      'peaks_json_url': instance.peaksJsonUrl,
      'genre_name': instance.genreName,
      'song_total_comment': instance.songTotalComment,
      'song_total_play': instance.songTotalPlay,
      'song_time_stamp': instance.songTimeStamp,
      'song_is_sponsor': instance.songIsSponsor,
      'album_url': instance.albumUrl,
      'is_on_profile': instance.isOnProfile,
      'profile_user_id': instance.profileUserId,
      'profile_page_id': instance.profilePageId,
      'user_server_id': instance.userServerId,
      'user_name': instance.userName,
      'full_name': instance.fullName,
      'gender': instance.gender,
      'user_image': instance.userImage,
      'is_invisible': instance.isInvisible,
      'user_group_id': instance.userGroupId,
      'language_id': instance.languageId,
      'last_activity': instance.lastActivity,
      'birthday': instance.birthday,
      'country_iso': instance.countryIso,
      'real_path': instance.realPath,
      'song_path64': instance.songPath64,
      'bookmark': instance.bookmark,
    };

ArtistUser _$ArtistUserFromJson(Map<String, dynamic> json) => ArtistUser(
      userId: json['user_id'] as String?,
      profilePageId: json['profile_page_id'] as String?,
      userServerId: json['user_server_id'] as String?,
      userName: json['user_name'] as String?,
      fullName: json['full_name'] as String?,
      gender: json['gender'] as String?,
      userImage: json['user_image'] as String?,
      isInvisible: json['is_invisible'] as String?,
      userGroupId: json['user_group_id'] as String?,
      languageId: json['language_id'] as String?,
      lastActivity: json['last_activity'] as String?,
      birthday: json['birthday'] as String?,
      countryIso: json['country_iso'] as String?,
    );

Map<String, dynamic> _$ArtistUserToJson(ArtistUser instance) =>
    <String, dynamic>{
      'user_id': instance.userId,
      'profile_page_id': instance.profilePageId,
      'user_server_id': instance.userServerId,
      'user_name': instance.userName,
      'full_name': instance.fullName,
      'gender': instance.gender,
      'user_image': instance.userImage,
      'is_invisible': instance.isInvisible,
      'user_group_id': instance.userGroupId,
      'language_id': instance.languageId,
      'last_activity': instance.lastActivity,
      'birthday': instance.birthday,
      'country_iso': instance.countryIso,
    };

LabelUser _$LabelUserFromJson(Map<String, dynamic> json) => LabelUser(
      userId: json['user_id'] as String?,
      profilePageId: json['profile_page_id'] as String?,
      userServerId: json['user_server_id'] as String?,
      userName: json['user_name'] as String?,
      fullName: json['full_name'] as String?,
      gender: json['gender'] as String?,
      userImage: json['user_image'] as String?,
      isInvisible: json['is_invisible'] as String?,
      userGroupId: json['user_group_id'] as String?,
      languageId: json['language_id'] as String?,
      lastActivity: json['last_activity'] as String?,
      birthday: json['birthday'] as String?,
      countryIso: json['country_iso'] as String?,
    );

Map<String, dynamic> _$LabelUserToJson(LabelUser instance) => <String, dynamic>{
      'user_id': instance.userId,
      'profile_page_id': instance.profilePageId,
      'user_server_id': instance.userServerId,
      'user_name': instance.userName,
      'full_name': instance.fullName,
      'gender': instance.gender,
      'user_image': instance.userImage,
      'is_invisible': instance.isInvisible,
      'user_group_id': instance.userGroupId,
      'language_id': instance.languageId,
      'last_activity': instance.lastActivity,
      'birthday': instance.birthday,
      'country_iso': instance.countryIso,
    };
